# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenSwift

  # Pod for OAuth with various services such as Spotify
  pod 'OAuthSwift', '~> 1.1.0'

  # Pod to process yaml files for API configuration
  pod 'Yaml'
end
